/**
 * Plaid SDK Assignment
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InstitutionsSearchPost200ResponseInstitutionsInner } from './institutionsSearchPost200ResponseInstitutionsInner';

export class InstitutionsSearchPost200Response {
    'institutions'?: Array<InstitutionsSearchPost200ResponseInstitutionsInner>;
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "institutions",
            "baseName": "institutions",
            "type": "Array<InstitutionsSearchPost200ResponseInstitutionsInner>"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InstitutionsSearchPost200Response.attributeTypeMap;
    }
}

