/**
 * Plaid SDK Assignment
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Additional options to filter institutions by various Payment Initiation configurations.
*/
export class InstitutionsSearchPostRequestOptionsPaymentInitiation {
    /**
    * A unique ID identifying the payment.
    */
    'paymentId'?: string;
    /**
    * A unique ID identifying the payment consent.
    */
    'consentId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "paymentId",
            "baseName": "payment_id",
            "type": "string"
        },
        {
            "name": "consentId",
            "baseName": "consent_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InstitutionsSearchPostRequestOptionsPaymentInitiation.attributeTypeMap;
    }
}

